version: 2
formats: all
python:
   version: 3.6
   install:
      - requirements: requirements.txt
      - method: pip
        path: .
   system_packages: true
submodules:
  include: all
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false